    input   [31:0]      paddr,
    input               pwrite,
    input               psel,
    input               penable,
    input   [31:0]      pwdata,
    output  [31:0]      prdata,
    output              pready,
    output              pslverr,
    output              interrupt,